### PR TITLE
Add options line to client configuration

### PR DESCRIPTION
**Pull request by z28cueball**
When logging on to DMR+ masters, an "options" line can specify default reflector/talkgroups.  Added this ability.
Rob, WX1N

### CODE REVIEW

**Comment by n0mjs710** [comment]
This doesn't send data to a DMR+ master. All you've done is added it to HBlink's internal data structure, without adding a way for it to be communicated to a DMR+ master.

**Comment by z28cueball** [comment]
Sorry about that Cort.  After looking at it some more, it looks like the options string needs to be sent as an "RPTO" packet, after the "RPTC" configuration packet has been sent.  Looking at the code, it looks like a section would need to be added similar to the RPTC packet section, with sending the packet, setting the status, and waiting for the acknowledgement.  I'm not overly familiar with the DMR protocol nor am I a programmer so I may be wrong.  Just thought I would put that out there in case someone else with more knowledge than me needs the functionality and wants to work on it, as I am not sure I'll be able to do it.

**Comment by n0mjs710** [comment]
Get me the protocol specification with that message type and I'll add it.

**Comment by z28cueball** [comment]
All I can find is that it's RPTO followed by a text string, I haven't been able to find a protocol specification for it. What about if I captured a network packet, would that provide enough info ?


-------- Original Message --------

**Comment by z28cueball** [comment]
Hi again Cort, I think I figured it out, and it seems to be working well.  I'm going to attempt to do another pull request.

**Pull request closed without merging**
